# Generated by Django 3.2.7 on 2022-02-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emobot', '0005_emotiontable_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotiontable',
            name='Time_Recorded',
            field=models.CharField(max_length=30),
        ),
    ]
